services:
  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail.yaml
      - /data/app_kn/etc:/var/log/odoo
    command: -config.file=/etc/promtail/promtail.yaml
    restart: always
