server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.10.10.235:3100/loki/api/v1/push

scrape_configs:
  - job_name: odoo
    static_configs:
      - targets:
          - localhost
        labels:
          job: odoo
          host: ${HOSTNAME}
          __path__: /var/log/odoo/server.log
